# Generated by Django 3.0.6 on 2020-06-05 04:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='content_en',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('advice_hint', wagtail.core.blocks.RichTextBlock()), ('warning_hint', wagtail.core.blocks.RichTextBlock()), ('content', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('codeblock', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML'), ('r', 'R')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], label='Code'))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='content_uk',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('advice_hint', wagtail.core.blocks.RichTextBlock()), ('warning_hint', wagtail.core.blocks.RichTextBlock()), ('content', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('codeblock', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML'), ('r', 'R')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], label='Code'))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='text_intro_en',
            field=wagtail.core.fields.RichTextField(default='Short description', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='text_intro_uk',
            field=wagtail.core.fields.RichTextField(default='Short description', max_length=300, null=True),
        ),
    ]
