# Generated by Django 3.0.7 on 2020-06-30 06:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200605_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='text_intro',
            field=wagtail.core.fields.RichTextField(default='Short description', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='text_intro_en',
            field=wagtail.core.fields.RichTextField(default='Short description', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='text_intro_uk',
            field=wagtail.core.fields.RichTextField(default='Short description', max_length=600, null=True),
        ),
    ]
